import { NextPage } from "next"
import { GetServerSideProps } from 'next'
import Head from "next/head"
import { readFile, stat} from "fs/promises"
import Link from "next/link"
import Layout from "../../components/Layout"
import Footer from "../../components/footer"
import { useProgressiveImg } from "../../hooks/blurImg"

interface Props{
  id: string
  content: {
    id: string,
    img: string,
    height: string,
    width: string,
    month: string,
    link?: string,
    year: string,
    safe_title: string,
    alt: string,
    title: string,
    day: string
  }
  prevID?: number
  nextId?: number
  PrevPage?: string
  nextPage?: string
}

const ComicId: NextPage<Props> = ({ id, content, prevID, nextId, PrevPage, nextPage }) => {

  const [src, { blur }] = useProgressiveImg("../../public/loading.svg", content.img)

  return (
    <>
      <Head>
        <title>Detail Comic { id}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex flex-col justify-start items-center mt-24 min-h-screen">
          <img
            src={src}
            alt={content.alt}
            style={{
              filter: blur ? "blur(20px)" : "none",
              transition: blur ? "none" : "filter 0.3s ease-out"
            }}
          />
          <div className="w-1/2 mt-12 flex flex-row justify-evenly gap-10">
            {PrevPage === 'fulfilled' &&
              <Link href={`/comics/${prevID}`}>
                <a>⬅ Previus</a>
              </Link>
            }
            {nextPage === 'fulfilled' &&
              <Link href={`/comics/${nextId}`}>
                <a>Next ➡</a>
              </Link>
            }
          </div>
        </div>
        <Footer></Footer>
      </Layout>

    </>
  )
}


export const getServerSideProps: GetServerSideProps = async (context) => {
  const { id } = context.query
  const file = await readFile(`${process.cwd()}/comicsJson/${id}.json`, "utf-8")
  const content = await JSON.parse(file)
  const idNumber = +id
  const prevID = idNumber - 1
  const nextId = idNumber + 1
  const [hasPrevPage, hasNextPage] = await Promise.allSettled([stat(`${process.cwd()}/comicsJson/${prevID}.json`),stat(`${process.cwd() }/comicsJson/${nextId}.json`)])
  const { status:PrevPage } = hasPrevPage
  const { status:nextPage} = hasNextPage
  return {
    props: { content, id, prevID, nextId, PrevPage, nextPage }
  }
}

export default ComicId